### ISSUE TITLE
Some errors from version 1.18.18

### ISSUE THREAD

**Issue by ewes** [SOFZP/show-solana-node-info_v2#1]
![Снимок экрана 2024-07-20 в 21 43 25](https://github.com/user-attachments/assets/f508bdda-2500-44c5-8928-11aa525a8787)

**Comment by SOFZP** [comment]
Done - https://github.com/SOFZP/show-solana-node-info_v2/commit/fa9123683b18bd2ff04f712eae07290fcba3c2c3


replaced kyc-api.vercel.app/api by api.solana.org/api

kyc-api.vercel.app is obsolete now, but api.solana.org is replaced it
